
<ul class="nav-offcanvas">
	<li>
		<div class="panel-group">
			<div class="panel panel-default">
				<a href="announcements.asp" class="panel-default"> 
					<div class="panel-heading">
						<h4 class="panel-title">View Announcements</h4>
					</div>
				</a>
			</div>
		</div>
	</li>
	<li>
		<div class="panel-group">
			<div class="panel panel-default">
				<a href="javascript:$('#email').val('guest@guest.com');$('#pass').val('123456');$('#loginfrm').submit();" class="panel-default"> 
					<div class="panel-heading">
						<h4 class="panel-title">Demo Dashboard</h4>
					</div>
				</a>
			</div>
		</div>
	</li>
	<li>
		<div class="panel-group">
			<div class="panel panel-default">
				<a href="about.asp" class="panel-default"> 
					<div class="panel-heading">
						<h4 class="panel-title">About</h4>
					</div>
				</a>
			</div>
		</div>
	</li>
</ul>